### ISSUE TITLE
The wallet sometimes does not receive transactions

### ISSUE THREAD

**Issue by ander7agar** [creativechain/android-wallet#2]
The wallet sometimes does not receive transactions. It is possible that the wallet does not connect to the only existing peer.

**Comment by fgallaire** [comment]
I have a transaction which is not seen by my wallet since the 2 august 2017.

**Comment by creativechain-git** [comment]
Hi Florent, from where to where you sent it? have you checked the transaction in the block explorer? Please check https://chainz.cryptoid.info/crea/ Exchanges need 150 confirmations
El 14 de agosto de 2017 a las 3:28 Florent Gallaire <notifications@github.com> escribió:I have a transaction which is not seen by my wallet since the 2 august 2017.

**Comment by fgallaire** [comment]
> Exchanges need 150 confirmations

1584 confirmations
As it's a withdraw from cryptopia, is it 2000 confirmations ?

**Comment by creativechain-git** [comment]
Supposedly Cryptopia no longer needs 2000 confirmations. Have you contacted their support?
El 14 de agosto de 2017 a las 15:01 Florent Gallaire <notifications@github.com> escribió:
Exchanges need 150 confirmations
1584 confirmations
As it's a withdraw from cryptopia, is it 2000 confirmations ?

**Comment by fgallaire** [comment]
I haven't contacted Cryptopia. But I would like to understand, as my coins are one a validated transaction on the blockchain, I don't see how Cryptopia could do something.

**Comment by creativechain-git** [comment]
This is very strange, since you should not need to reach 2000 confirmations. Did you get the last version of the wallet? Also, have you checked if the receiving address is correct?You can contact @ridjaldiallo through Telegram to have more direct conversation about this issue.
El 14 de agosto de 2017 a las 15:16 Florent Gallaire <notifications@github.com> escribió:I haven't contacted Cryptopia. But I would like to understand, as my coins are one a validated transaction on the blockchain, I don't see how Cryptopia could do something.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/creativechain/android-wallet","title":"creativechain/android-wallet","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/creativechain/android-wallet"}},"updates":{"snippets":[{"icon":"PERSON","message":"@fgallaire in #2: I haven't contacted Cryptopia. But I would like to understand, as my coins are one a validated transaction on the blockchain, I don't see how Cryptopia could do something."}],"action":{"name":"View Issue","url":"https://github.com/creativechain/android-wallet/issues/2#issuecomment-322186901"}}}

**Comment by fgallaire** [comment]
The  ``Reset blockchain`` option worked fine for me.
